# Generated by Django 6.0.7 on 2026-07-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('model', models.CharField()),
                ('year', models.IntegerField()),
                ('info', models.CharField()),
            ],
        ),
    ]
