from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def c_class(request):
    return HttpResponse("The Mercedes-Benz C-Class is a series of compact executive cars produced by Mercedes-Benz Group AG. Introduced in 1993 as a replacement for the 190 (W201) range, the C-Class was the smallest model in the marque's line-up until the W168 A-Class arrived in 1997. The C-Class has been available with a 4MATIC four-wheel drive option since 2002. The third generation (W204) was launched in 2007 while the current W206 generation was launched in 2021. The upcoming W520 was unveiled in 2026 with sales starting in 2027.[1] Initially available in sedan and station wagon configurations, a fastback coupé (SportCoupé) variant followed and was later renamed to Mercedes-Benz CLC-Class. It remained in production until 2011 when a new W204 C-Class coupé replaced it for the 2012 model year.")

def a_class(request):
    return HttpResponse("The Mercedes-Benz A-Class is a car manufactured by German luxury automaker Mercedes-Benz. It has been marketed across four generations as a front-engine, front-wheel drive, five-passenger, five-door hatchback, with a three-door hatchback offered for the second generation, as well as a saloon version for the fourth. As the brand's entry-level vehicle, the first generation A-Class, internally coded W168, was introduced in 1997, the second generation (W169) in late 2004 and the third generation (W176) in 2012. The fourth generation model (W177), which was launched in 2018, marked the first time the A-Class was offered in the United States and Canada.[1] This fourth generation A-Class is also the first to be offered both as a hatchback (W177) and sedan (V177).[2] Styled by Steve Mattin and launched at the 1997 Frankfurt Motor Show, the A-Class was noted for its short, narrow footprint, its overall height, and an interior volume and level of equipment competing with larger cars. The A-Class subsequently gained length and width over its successive generations, losing some of its height. Approximately 3.3 million A-Class models had been manufactured by the 2021 model year.")

def cla(request):
    return HttpResponse("The Mercedes-Benz CLA is a series of luxury subcompact executive cars manufactured by Mercedes-Benz since 2013. The first generation was a four-door sedan based on the platform of the W176 A-Class and W246 B-Class compact cars, marketed as a four-door coupé.[1] In 2015, Mercedes-Benz expanded the CLA family to include a station wagon configuration which it markets as a Shooting Brake.[2] The CLA is Mercedes-Benz's first front-wheel drive vehicle offered in the American market. The CLA range is positioned above the A-Class and it is nearly on the level of the C-Class in the Mercedes model range, and models tend to be less practical than the A-Class it is based on.[3] The CLA first went on sale in Europe in April 2013, and was subsequently introduced in the United States in September 2013.[4] Its largest markets are Western Europe and the United States.[4] Global cumulative CLA sales reached 100,000 during its first year,[4] cited as our best launch in 20 years by Mercedes-Benz.[5] Worldwide, Mercedes-Benz sold about 750,000 units of the first generation.[6]")
