# Generated by Django 6.1 on 2026-09-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_current_user',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
