name = input("enter your name: ")
print(name)
age=input("enter your age")
print(age)
surname =input("enter your surname")
print(surname)
color = input("enter your color")
print(color)
num = input("enter your num")
print(num)